source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseDB
 pod 'Firebase'
 pod 'Firebase/Auth'
 pod ‘Firebase/Database’
 pod 'SnapKit'
end
